-- Run this in Supabase SQL Editor to fix the FK constraint error immediately

-- Step 1: Clean up invalid data
UPDATE loads SET assigned_vehicle_id = NULL WHERE assigned_vehicle_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM wialon_vehicles WHERE id = loads.assigned_vehicle_id);
UPDATE calendar_events SET assigned_vehicle_id = NULL WHERE assigned_vehicle_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM wialon_vehicles WHERE id = calendar_events.assigned_vehicle_id);

-- Step 2: Add FK constraint if missing
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'loads_assigned_vehicle_id_fkey') THEN ALTER TABLE loads ADD CONSTRAINT loads_assigned_vehicle_id_fkey FOREIGN KEY (assigned_vehicle_id) REFERENCES wialon_vehicles(id) ON DELETE SET NULL; END IF; END $$;

-- Step 3: Fix the trigger
CREATE OR REPLACE FUNCTION sync_load_to_calendar_events() RETURNS TRIGGER AS $$ DECLARE v_pickup_event_id UUID; v_delivery_event_id UUID; v_validated_vehicle_id UUID; BEGIN IF NEW.assigned_vehicle_id IS NOT NULL THEN SELECT id INTO v_validated_vehicle_id FROM wialon_vehicles WHERE id = NEW.assigned_vehicle_id; IF v_validated_vehicle_id IS NULL THEN v_validated_vehicle_id := NULL; END IF; ELSE v_validated_vehicle_id := NULL; END IF; IF NEW.pickup_datetime IS NOT NULL OR NEW.expected_arrival_at_pickup IS NOT NULL THEN SELECT id INTO v_pickup_event_id FROM calendar_events WHERE load_id = NEW.id AND event_type = 'pickup' LIMIT 1; IF v_pickup_event_id IS NOT NULL THEN UPDATE calendar_events SET start_time = COALESCE(NEW.expected_arrival_at_pickup, NEW.pickup_datetime), end_time = COALESCE(NEW.expected_departure_from_pickup, NEW.pickup_datetime + INTERVAL '2 hours'), assigned_vehicle_id = v_validated_vehicle_id, notes = CONCAT('Load: ', NEW.load_number, ' | Origin: ', NEW.origin), updated_at = NOW() WHERE id = v_pickup_event_id; ELSE INSERT INTO calendar_events (load_id, event_type, start_time, end_time, assigned_vehicle_id, notes) VALUES (NEW.id, 'pickup', COALESCE(NEW.expected_arrival_at_pickup, NEW.pickup_datetime), COALESCE(NEW.expected_departure_from_pickup, NEW.pickup_datetime + INTERVAL '2 hours'), v_validated_vehicle_id, CONCAT('Load: ', NEW.load_number, ' | Origin: ', NEW.origin)); END IF; END IF; IF NEW.delivery_datetime IS NOT NULL OR NEW.expected_arrival_at_delivery IS NOT NULL THEN SELECT id INTO v_delivery_event_id FROM calendar_events WHERE load_id = NEW.id AND event_type = 'delivery' LIMIT 1; IF v_delivery_event_id IS NOT NULL THEN UPDATE calendar_events SET start_time = COALESCE(NEW.expected_arrival_at_delivery, NEW.delivery_datetime), end_time = COALESCE(NEW.expected_departure_from_delivery, NEW.delivery_datetime + INTERVAL '2 hours'), assigned_vehicle_id = v_validated_vehicle_id, notes = CONCAT('Load: ', NEW.load_number, ' | Destination: ', NEW.destination), updated_at = NOW() WHERE id = v_delivery_event_id; ELSE INSERT INTO calendar_events (load_id, event_type, start_time, end_time, assigned_vehicle_id, notes) VALUES (NEW.id, 'delivery', COALESCE(NEW.expected_arrival_at_delivery, NEW.delivery_datetime), COALESCE(NEW.expected_departure_from_delivery, NEW.delivery_datetime + INTERVAL '2 hours'), v_validated_vehicle_id, CONCAT('Load: ', NEW.load_number, ' | Destination: ', NEW.destination)); END IF; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
